version: '3.7'

services:

  redis:
    restart: always
    image: redis:6.0.8
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=news"
    ports:
      - 45432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080